version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: on-failure
    ports:
      - '${MONGODB_PORT}:${MONGODB_PORT}'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    env_file:
      - .env
    ports:
      - '${API_PORT}:${API_PORT}'
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@mongodb:${MONGODB_PORT}/${MONGODB_DATABASE}?authSource=admin
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    name: flights-mongodb-data
